const LOGIN_LOADING = 'LOGIN_LOADING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

const USER_FETCH_LOADING = 'USER_FETCH_LOADING';
const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
const USER_FETCH_ERROR = 'USER_FETCH_ERROR';

const LOGOUT = 'LOGOUT';

export {
	LOGIN_LOADING,
	LOGIN_SUCCESS,
	LOGIN_ERROR,
	USER_FETCH_LOADING,
	USER_FETCH_SUCCESS,
	USER_FETCH_ERROR,
	LOGOUT,
};
